spring:
  address: localhost
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/healdb
    username: root
    password: 123456

  flyway:
    url: jdbc:mysql://localhost:3306/healdb
    user: root
    password: 123456
    baselineOnMigrate: true

client:
  catalog:
    base-url: "http://localhost:8081"
    overview-path: "/api/v1/available-services/{service-id}"
    overview-by-doctor-id-path: "/api/v1/available-services/doctors/{doctor-id}"
    create-doctor-path: "/api/v1/available-services/doctors"
  user:
    base-url: "http://localhost:8080"
    get-patient-by-id-path: "/api/v1/patients/{patient-id}"
    patient-by-uuids-path: "/api/v1/patients/info"

sec-env-conf:
  enable-login-guard: true

server:
  port: 8082